apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName}}
  rules:
    - host: {{ .Values.ingress.backend.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.backend.name }}
                port:
                  number: 80
    - host: {{ .Values.ingress.frontend.host }}
      http:
        paths:
          - path: /
            pathType: Prefix 
            backend:
              service:
                name: {{ .Values.service.frontend.name }}
                port:
                  number: {{ .Values.service.frontend.port }}
    - host: {{ .Values.ingress.queue.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: 
              service:
                name: {{ .Values.service.queue.name }}
                port:
                  number: {{ .Values.service.queue.port}}