apiVersion: v1
kind: PersistentVolume
metadata:
  name: finbly-postgresql-pv
  namespace: finbly
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/finbly
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - worker-node