apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: finbly-postgresql-pvc
  namespace: finbly
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  storageClassName: ""
  volumeName: finbly-postgresql-pv
