apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: finbly-postgres-pvc
  namespace: finbly
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  storageClassName: "local-path"
