apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: finbly-postgres
  namespace: finbly
  labels:
    app: finbly-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finbly-postgres
  template:
    metadata:
      labels:
        app: finbly-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: finbly-postgres-password
                  key: password
          volumeMounts:
            - name: db-volume
              mountPath: /var/lib/postgres/data
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: finbly-postgres-pvc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: finbly-rabbitmq
  namespace: finbly
  labels:
    app: finbly-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finbly-rabbitmq
  template:
    metadata:
      labels:
        app: finbly-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "admin"
            - name: RABBITMQ_DEFAULT_PASS
              value: "admin"
