apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.configMapName}}
data:
  default.conf: | 
    server {
      listen      80;
      listen [::]:80;
      server_name localhost;

      root        /opt/finbly-frontend;
      index       index.html index.htm index.php;

      location /_next/ {
          root /opt/finbly-frontend;
      }

      location /static/ {
          root /opt/finbly-frontend;
      }

      location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|otf|webp)$ {
          root /opt/finbly-frontend;
          access_log off;
          expires 1d;
          add_header Cache-Control "public, immutable";
      }

      error_log   /var/log/nginx/error.log warn;
      access_log  /var/log/nginx/access.log main;
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: finbly-init-sql
  namespace: {{ .Values.namespace }}
data:
  init.sql: |
    DO
    $$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'finbly') THEN
        CREATE USER finbly WITH PASSWORD 'sua_senha';
      END IF;
    END
    $$;

    -- Criação condicional do banco usando psql puro (não DO block)
    \connect postgres
    SELECT 'CREATE DATABASE finblydb OWNER finbly'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'finblydb')
    \gexec

    DO
    $$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_database WHERE datname = 'finblydb') THEN
        CREATE DATABASE finblydb OWNER finbly;
      END IF;
    END
    $$;
