apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.deployment.backend.name }}
  labels:
    app: {{ .Values.deployment.backend.name }}
spec:
  replicas: {{ .Values.deployment.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.backend.name }}
    spec:
      containers:
        - name: {{ .Values.deployment.backend.name }}
          image: {{ .Values.deployment.backend.image }}
          ports:
            - containerPort: {{ .Values.deployment.backend.port }}
          env:
            - name: DB_TYPE
              value: {{ .Values.service.database.type }}
            - name: DB_HOST
              value: {{ .Values.service.database.name }}
            - name: DB_USER
              value: {{ .Values.databaseName}}
            - name: DB_SCHEMA
              value: {{ .Values.databaseName}}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  - name: {{ .Values.secret.database.name }}
                    key: password
            - name: RABBITMQ_HOST
              value: {{ .Values.service.queue.name}}
          resources:
            requests:
              cpu: {{ .Values.deployment.backend.cpu }}
              memory: {{ .Values.deployment.backend.memory }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.deployment.frontend.name }}
  labels:
    app: {{ .Values.deployment.frontend.name }}
spec:
  replicas: {{ .Values.deployment.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.frontend.name }}
    spec:
      containers:
        - name: {{ .Values.deployment.frontend.name }}
          image: {{ .Values.deployment.frontend.image }}
          ports:
            - containerPort: {{ .Values.deployment.frontend.port }}
          resources:
            requests:
              cpu: {{ .Values.deployment.frontend.cpu }}
              memory: {{ .Values.deployment.frontend.memory }}
          volumeMounts:
            - name: finbly-frontend-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
      volumes:
        - name: finbly-frontend-config
          configMap:
            name: {{ .Values.configMapName }}