apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.database.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.pvc.database.storage }}
  storageClassName: "local-path"