apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.service.backend.name }}
spec:
  selector:
    app: {{ .Values.deployment.backend.name }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.deployment.backend.port }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.service.frontend.name }}
spec:
  selector:
    app: {{ .Values.deployment.frontend.name }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.deployment.frontend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.database.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.statefulSet.database.name}}
  ports:
    - name: db
      protocol: TCP
      port: {{ .Values.statefulSet.database.port }}
      targetPort: {{ .Values.statefulSet.database.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.queue.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.statefulSet.queue.name }}
  ports:
    - name: amqp
      protocol: TCP
      port: {{ .Values.statefulSet.queue.amqpPort }}
      targetPort: {{ .Values.statefulSet.queue.amqpPort }}
    - name: management
      protocol: TCP
      port: {{ .Values.statefulSet.queue.adminPort }}
      targetPort: {{ .Values.statefulSet.queue.adminPort }}
