apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.namespace }}
  namespace: finbly
  labels:
    app: {{ .Values.statefulSet.database.name }}
spec:
  replicas: {{ .Values.statefulSet.database.replcas }}
  selector:
    matchLabels:
      app: {{ .Values.statefulSet.database.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.statefulSet.database.name }}
    spec:
      containers:
        - name: {{ .Values.statefulSet.database.name }}
          image: {{ .Values.statefulSet.database.image }}
          ports:
            - containerPort: {{ .Values.statefulSet.database.port }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.database.name }}
                  key: password
          volumeMounts:
            - name: db-volume
              mountPath: /var/lib/postgres/data
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.database.name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulSet.queue.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.statefulSet.queue.name }}
spec:
  replicas: {{ .Values.statefulSet.queue.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.statefulSet.queue.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.statefulSet.queue.name }}
    spec:
      containers:
        - name: {{ .Values.statefulSet.queue.name }}
          image: {{ .Values.statefulSet.queue.image }}
          ports:
            - containerPort: {{ .Values.statefulSet.queue.amqpPort }}
            - containerPort: {{ .Values.statefulSet.queue.adminPort }}
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "admin"
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.queue.name }}
                  key: password
